add intelligent-search-api-middleware recipe
vtex-apps/io-documentation pull request #1388
Opened 2022-07-18 15:08 UTC by hiagolcm

**What problem is this solving?**

We are releasing the `Intelligent Search Middleware` feature. This PR adds a recipe showing how to use this feature.

2022-09-02 14:23 UTC, karenkrieger requested changes

2022-09-02 14:23 UTC, karenkrieger commented on docs/en/Recipes/store-management/intelligent-search-middleware.md
> +description: "This guide will show you how to create a middleware for the Intelligent Search API. This way, you will be able to change the request that comes from the client"
```suggestion
description: "This guide will show you how to create a middleware for the Intelligent Search API. This way, you will be able to change the request that comes from the client."
```

2022-09-02 14:23 UTC, karenkrieger commented on docs/en/Recipes/store-management/intelligent-search-middleware.md
> +In some situations you may want to change the Intelligent Search API request that comes from the client. For example: "If the client searches for shoes, I want to promote the productId 123". This is
```suggestion
In some situations you may want to change the Intelligent Search API request that comes from the client. For example: "If the client searches for shoes, I want to promote the `productId` 123". This is possible with the Intelligent Search Middlewares.
```

2022-09-02 14:23 UTC, karenkrieger commented on docs/en/Recipes/store-management/intelligent-search-middleware.md
> +7. From now on, every time a user searches for `shoes`, the intelligent search will promote the product `123`.
```suggestion
7. From now on, every time a user searches for `shoes`, the Intelligent Search will promote the product `123`.
```

2022-10-13 16:39 UTC, karenkrieger requested changes

2022-10-13 16:39 UTC, karenkrieger commented on docs/en/Recipes/store-management/intelligent-search-middleware.md
> +To create an IS API middleware, you need to create a new VTEX IO app from the [`vtex.is-api-middleware-resolver`](https://github.com/vtex-apps/is-api-middleware-resolver) boilerplate and customize it
```suggestion
To create an Intelligent Search API middleware, you need to create a new VTEX IO app from the [`vtex.is-api-middleware-resolver`](https://github.com/vtex-apps/is-api-middleware-resolver) boilerplate and customize it to establish your own rules, according to the following steps:
```

2022-10-13 16:39 UTC, karenkrieger commented on docs/en/Recipes/store-management/intelligent-search-middleware.md
> +7. From now on, every time a user searches for `shoes`, the Intelligent Search will promote the product `123`.
```suggestion
From now on, every time a user searches for `shoes`, the Intelligent Search will promote the product `123`.
```

2022-10-13 16:39 UTC, karenkrieger commented on docs/en/Recipes/store-management/intelligent-search-middleware.md
> +7. From now on, every time a user searches for `shoes`, the Intelligent Search will promote the product `123`.
Como isso é uma conclusão e não uma etapa, tirava da lista

2022-10-13 18:43 UTC, hiagolcm commented on docs/en/Recipes/store-management/intelligent-search-middleware.md
> +7. From now on, every time a user searches for `shoes`, the Intelligent Search will promote the product `123`.
Bom ponto!

2022-10-13 18:50 UTC, karenkrieger approved these changes
LGTM

2022-10-13 18:55 UTC, merged