add price async recipe
vtex-apps/io-documentation pull request #737
Opened 2020-10-22 13:43 UTC by hiagolcm

**What problem is this solving?**

We are implementing a new feature to the product-summary: the [asynchronous price](https://github.com/vtex-apps/product-summary/pull/280). This PR adds a guide to help the developer to implement this functionality.

**How should this be manually tested?**
[workspace](hiago--storecomponents.myvtex.com)

**Screenshots or example usage:**
![priceasync](https://user-images.githubusercontent.com/40380674/96735041-85265680-1391-11eb-80e9-2eb35607fd72.gif)

2020-10-22 15:10 UTC, klzns requested changes

2020-10-22 15:10 UTC, klzns commented on docs/en/Recipes/layout/async-price.md
> +}
```suggestion
  "product-summary.shelf": {
    "props": {
     "isPriceAsync": true
    },
    "children": [
      // other children
-     "product-list-price#summary",
-     "flex-layout.row#selling-price-savings",
-     "product-installments#summary",
-     "add-to-cart-button",
+     "product-price-suspense"
   ]
  },
+ "product-price-suspense": {
+   "children": [
+     "product-list-price#summary",
+     "flex-layout.row#selling-price-savings",
+     "product-installments#summary",
+     "add-to-cart-button"
+   ]
+ },
}
```

2020-10-22 15:10 UTC, klzns commented on docs/pt/Recipes/layout/preco-assincrono.md
> +  }
Same as above

2020-10-22 15:10 UTC, klzns commented on docs/pt/Recipes/layout/preco-assincrono.md
> +tags: ["price", "simulation"]
No need for this one, we only render in English

2020-10-22 15:10 UTC, klzns commented on docs/en/Recipes/layout/async-price.md
> +4. Wrap the price information in the `product-price-suspense`.
```suggestion
4. Wrap the price blocks in the `product-price-suspense`.
```

2020-10-22 16:50 UTC, hiagolcm commented on docs/pt/Recipes/layout/preco-assincrono.md
> +tags: ["price", "simulation"]
You mean the whole file, right?
Done 👍

2020-11-09 18:53 UTC, klzns approved these changes

2020-11-10 18:20 UTC, merged