Create getting-started-with-lighthouse.md
vtex-apps/io-documentation pull request #766
Opened 2020-12-02 23:40 UTC by carolinamenezes

**What problem is this solving?**

**How should this be manually tested?**

**Screenshots or example usage:**

2020-12-03 14:52 UTC, gris approved these changes
Tá maneira demais a doc 🚀 ! Acho que um quick win para ela que podemos entender na próxima sync de documentação do IO como fazer é mapear cada métrica com funcionalidades de performance que disponibilizamos hoje, o que acha?

2020-12-03 14:52 UTC, gris commented on docs/en/Recipes/store-management/getting-started-with-lighthouse.md
> +Lazy loading content below-the-fold is a good practice for improving LCP. That's because lazy loading focuses network bandwidth on the content above-the-fold and guarantees that no large stray elemen
O que acha de linkar aqui para essa doc? https://vtex.io/docs/recipes/templates/using-the-fold-blocks/

2020-12-03 14:52 UTC, gris commented on docs/en/Recipes/store-management/getting-started-with-lighthouse.md
> +This metric is mostly affected by images, ads, embeds, and iframes without pre-defined dimensions, and content dynamically inserted by JS on the client-side (e.g. a bar that suddenly appears on the h
O que acha de botar uma seção no final linkando para essa doc https://vtex.io/docs/recipes/store-management/best-practices-for-optimizing-performance/?

2020-12-28 16:56 UTC, gris requested changes

2020-12-28 16:56 UTC, gris commented on docs/en/Recipes/store-management/debugging-performance-issues.md
> +Before proceeding, we recommend that you run [Lighthouse](https://developers.google.com/speed/pagespeed/insights/), considering the production workspace you're currently working in, by using the foll
Nessa seção, acho que vale um heads up dizendo que se a loja já tiver em produção para rodar com o domínio da loja que o usuário final acessa. Até poque o pagespeed insights só funciona com domínio público.

2020-12-28 16:56 UTC, gris commented on docs/en/Recipes/store-management/debugging-performance-issues.md
> +However,  it is important to remember that JavaScript handles data fetching, templating, and routing on the client-side rather than on the server-side.
```suggestion
However, it is important to remember that JavaScript handles data fetching, templating, and routing on the client-side rather than on the server-side.
```

2020-12-28 16:56 UTC, gris commented on docs/en/Recipes/store-management/debugging-performance-issues.md
> +One of the first actions to debug performance issues is to test the desired page without *Pixel apps*.
Talvez linkar para essa doc https://vtex.io/docs/concepts/pixel-app/

2021-04-07 16:34 UTC, carolinamenezes commented on docs/en/Recipes/store-management/debugging-performance-issues.md
> +After enabling the critical CSS optimization, you can check if it's being delivered by ensuring the page is being server-side rendered (Step 1) and searching for the style tag `<style id="critical" t
```suggestion
VTEX IO offers the option of [enabling critical CSS optimization](https://developers.vtex.com/vtex-developer-docs/docs/vtex-io-documentation-best-practices-for-optimizing-performance#optimizing-critical-css) in home pages, product pages, and product listing pages. This feature allows the browser to find the minimum CSS code blocks needed to display the page's critical content first. Meanwhile, the remainder CSS code is loaded asynchronously.

>ℹ️ Critical, also known as above-the-fold, refers to the portion of a web page a user sees when first loading a page. Notice that, for a good user experience, the critical content needs to be loaded quickly. Follow [this link](https://developers.vtex.com/vtex-developer-docs/docs/vtex-io-documentation-best-practices-for-optimizing-performance#optimizing-critical-css) to learn how to optimize critical CSS.

Critical CSS optimization requires that the page is server-side rendered and that CSS concatenation is enabled. Also, the process of optimizing CSS for each page can take some time and varies depending on the page and viewport size.

>⚠️ CSS optimization may not respond immediately. Only after different users access the same page using a similar viewport will the CSS's optimized version take effect. Take product pages as an example: some products may have SKU selectors, while others don't. Since it isn't necessary to serve SKU selector styles for product pages that don't have this component, product pages might not share the same critical optimization. Similarly, two users accessing the same page using different devices, such as mobile and desktop, won't share the same optimization.

Hence, after enabling the critical CSS optimization, check if your pages are being optimized:

1. Make sure your pages are server-side rendered (Step 1)
2. Look for the style tag `<style id="critical" type="text/css">` inside the `<head>` tag of the corresponding pages. 
```

2021-04-07 16:52 UTC, carolinamenezes commented on docs/en/Recipes/store-management/debugging-performance-issues.md
> +One of the first actions to debug performance issues is to test the desired page without *Pixel apps*.
```suggestion
One of the first actions to debug performance issues is to test the desired page without [Pixel apps](https://developers.vtex.com/vtex-developer-docs/docs/vtex-io-documentation-pixel-app).
```

2021-04-07 17:00 UTC, carolinamenezes commented on docs/en/Recipes/store-management/getting-started-with-lighthouse.md
> +This metric is mostly affected by images, ads, embeds, and iframes without pre-defined dimensions, and content dynamically inserted by JS on the client-side (e.g. a bar that suddenly appears on the h
```suggestion
This metric is mostly affected by images, ads, embeds, and iframes without pre-defined dimensions, and content dynamically inserted by JS on the client-side (e.g. a bar that suddenly appears on the header).

---
If you want to learn more, check our [best practices for optimizing performance.](https://developers.vtex.com/vtex-developer-docs/docs/vtex-io-documentation-best-practices-for-optimizing-performance)

```

2021-04-07 18:15 UTC, carolinamenezes commented on docs/en/Recipes/store-management/debugging-performance-issues.md
> +Before proceeding, we recommend that you run [Lighthouse](https://developers.google.com/speed/pagespeed/insights/), considering the production workspace you're currently working in, by using the foll
```suggestion
Before proceeding any further, we recommend that you run [Lighthouse](https://developers.google.com/speed/pagespeed/insights/) using the following URL pattern `https://{account}.myvtex.com/?workspace={workspace}`, given the production workspace you're currently working, and take note of your store's performance. You can also analyze the store in production. In this case, please consider the URL available to end-users. 
```

2021-04-07 18:16 UTC, merged